### ISSUE TITLE
[priority:p0] Distribution invariant check failure

### ISSUE THREAD

**Issue by HaoyangLiu** [irisnet/irishub#1035]
E[10016-01-10|10:50:31.184] CONSENSUS FAILURE!!!                         module=consensus err="invariant broken: delegator accum invariance: 
	validator key: fva1fee6gps7f0ud7vlqfdjq823tkrsexqckt5tfe0
	validator: {OperatorAddr:4E73A4061E4BF8DF33E04B6403AA2BB0E1930316 ConsPubKey:PubKeyEd25519{06EDF9E3C50A67BF427BEA7195AE043AF1AF9AAE30E335D365BBF4568DCBB73C} Jailed:true Status:1 Tokens:+100050000000000000000000000000000 DelegatorShares:+100050000000000000000000000000000 Description:{Moniker:node0 Identity: Website: Details:} BondHeight:0 UnbondingHeight:206 UnbondingMinTime:2019-01-31 10:48:09.613994417 +0000 UTC Commission:rate: 1000000000, maxRate: 2000000000, maxChangeRate: 100000000, updateTime: 0001-01-01 00:00:00 +0000 UTC}
	sum delegator accum: 460000000000000000000000.0000000000
	validator's total delegator accum: 230000000000000000000000.0000000000
	log of delegations with accum: 
	\tdel: faa1ljemm0yznz58qxxs8xyak7fashcfxf5lssn6jm, accum: 460000000000000000000000.0000000000, power: 100000000000000000000000000000000\n" stack="goroutine 6774 [running]:\nruntime/debug.Stack(0xc0037c1290, 0xee39c0, 0xc00389fbf0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000922a80, 0x11a60a8)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xee39c0, 0xc00389fbf0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).assertRuntimeInvariants(0xc0008baa00, 0x12abc60, 0xc003a2a960, 0xc00018fa80, 0xd)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/app/v0/invariants.go:36 +0x340\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker(0xc0008baa00, 0x12abc60, 0xc003a2a960, 0xc00018fa80, 0xd, 0xe5, 0x0, 0x0, 0x0, 0x0, ...)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:281 +0x401\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker-fm(0x12abc60, 0xc003a2a960, 0xc00018fa80, 0xd, 0xe5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:394 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc00009a480, 0xe5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/app/baseapp.go:833 +0x899\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000868360, 0xe5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0000b2ef0, 0xe5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x12aca60, 0xc001e46060, 0x12b1de0, 0xc0000b2ef0, 0xc0023f6d20, 0xc003a2a2a0, 0x12b6480, 0xc00000e4c0, 0x19, 0xc003041000, ...)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:279 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00196bb90, 0x8, 0x0, 0xc001965a90, 0x6, 0xc001965ab0, 0xc, 0xe4, 0x19, 0xc003041000, ...)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000922a80, 0xe5)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000922a80, 0xe5)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000922a80, 0x0, 0xe5)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000922a80, 0xe5, 0x0)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000922a80, 0xc0008381e0, 0xc000907b30, 0x28, 0x11a72e8, 0x107, 0xc0037c3ac0)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000922a80, 0xc0008381e0, 0xc000907b30, 0x28, 0xc000174d80, 0x107, 0x107)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000922a80, 0x12a0160, 0xc004139548, 0xc000907b30, 0x28)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000922a80, 0x0)
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:619 +0x682\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart
	/home/liuhequn2018/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Comment by HaoyangLiu** [comment]
There are some defects in the fix for PR https://github.com/irisnet/irishub/pull/1019
https://github.com/irisnet/irishub/blob/d36cd6ec36cc387951eec53775b78d88f6d1bd02/modules/distribution/keeper/validator.go#L84
```
} else {
		vi := k.GetValidatorDistInfo(ctx, operatorAddr)
		vi.DelAccum.UpdateHeight = ctx.BlockHeight()
		k.SetValidatorDistInfo(ctx, vi)
	}
```
