### ISSUE TITLE
[priority:p0] Error flushing consensus wal buf to file

### ISSUE THREAD

**Issue by HaoyangLiu** [irisnet/irishub#1050]
E[11016-01-11|18:32:20.137] CONSENSUS FAILURE!!!                         module=consensus err="Error flushing consensus wal buf to file. Error: open iris/data/cs.wal/wal: no such file or directory \n" stack="goroutine 1231 [running]:\nruntime/debug.Stack(0xc003b72b18, 0xe98ce0, 0xc0009b15b0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000183180, 0x11a4c08)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xe98ce0, 0xc0009b15b0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*baseWAL).WriteSync(0xc002a412c0, 0xf1e020, 0xc003c48be8)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/wal.go:144 +0x110\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000183180, 0x39)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1292 +0x8b4\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000183180, 0x39)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000183180, 0x0, 0x39)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000183180, 0x39, 0x0)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000183180, 0xc002a797c0, 0xc0001ba1b0, 0x28, 0x11a5e48, 0x105, 0xc003b73ac0)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000183180, 0xc002a797c0, 0xc0001ba1b0, 0x28, 0xc0024558c0, 0x105, 0x105)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000183180, 0x129f6e0, 0xc002b2b8f0, 0xc0001ba1b0, 0x28)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000183180, 0x0)\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:619 +0x682\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Comment by HaoyangLiu** [comment]
This issue caused by wrong operation. Not a bug.
