### ISSUE TITLE
[p1] Shutting down tmkms when a validator enters proposal round crashes the app

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1460]
**Describe the bug**
Panic happened while trying to shutdown `tmkms` server in proposal round.

**NOTICE！！  This “CONSENSUS FAILURE” will not affect the consensus of other nodes.**

**Screenshots**
[22056-05-22|19:58:40.607] CONSENSUS FAILURE!!!                         module=consensus err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 2109 [running]:\nruntime/debug.Stack(0x58930c0, 0x3ff0000000000000, 0x2)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc0000adc00, 0x4e5f5a8)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:584 +0x12a\npanic(0x4ba8800, 0x585c250)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/tendermint/tendermint/privval.(*RemoteSignerClient).GetPubKey(...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/privval/remote_signer.go:55\ngithub.com/tendermint/tendermint/privval.(*SocketVal).GetPubKey(0xc0001bb100, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/privval/client.go:89 +0x72\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterPropose(0xc0000adc00, 0x163, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:846 +0x594\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterNewRound(0xc0000adc00, 0x163, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:796 +0x7d2\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc0000adc00, 0xc003b18be0, 0xc00086ea20, 0x28, 0x6241460, 0xc0008e7ad8, 0xc0008e7b18)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:1635 +0xadc\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc0000adc00, 0xc003b18be0, 0xc00086ea20, 0x28, 0x106, 0x106, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:1484 +0x5c\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc0000adc00, 0x4fd6180, 0xc0015a1798, 0xc00086ea20, 0x28)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:663 +0x6cc\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc0000adc00, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:620 +0x65f\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/consensus/state.go:306 +0x12b\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46f9336]

goroutine 82 [running]:
github.com/tendermint/tendermint/privval.(*RemoteSignerClient).Ping(0x0, 0x4e60980, 0xc0001bb168)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/privval/remote_signer.go:133 +0x36
github.com/tendermint/tendermint/privval.(*SocketVal).Ping(0xc0001bb100, 0x0, 0x0)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/privval/client.go:113 +0x7a
github.com/tendermint/tendermint/privval.(*SocketVal).OnStart.func1(0xc0001bb100)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/privval/client.go:152 +0xc8
created by github.com/tendermint/tendermint/privval.(*SocketVal).OnStart
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.0/privval/client.go:148 +0x269

version 0.14.0

**Comment by shilei-wang** [comment]
Cannot reproduce
