### ISSUE TITLE
[p0] Sending native tokens to <commulity_tax_add> and initiate a "TxTaxUsage/Burn" proposal causes CONSENSUS FAILURE!

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1654]
**Describe the bug**
We fix the bug https://github.com/irisnet/irishub/issues/1578 , but still need to take this scenario into account,otherwise,the consequences are very serious!

**To Reproduce**
```
iriscli asset issue-token --family=fungible --source=native --symbol-min-alias=alias --name=token-name --initial-supply=10000 --from=v0 --chain-id=shilei-qa --fee=0.004iris --commit --symbol=btc

iriscli bank send --amount=1btc --fee=0.004iris --commit --chain-id=shilei-qa --from=v0 --to=faa18rtw90hxz4jsgydcusakz6q245jh59kfrjhp52

iriscli gov submit-proposal --chain-id=shilei-qa --from=v0 --fee=0.05iris --commit --deposit="1000iris" --description="test"  --title="burn tokens 5%" --type="TxTaxUsage" --usage="Burn" --percent=0.05

iriscli gov vote --fee=0.004iris --commit --from=v0 --chain-id=shilei-qa  --proposal-id=1  --option=Yes
```

CONSENSUS FAILURE!!!                         module=consensus err="total loosen token is negative" stack="goroutine 33 [running]:\nruntime/debug.Stack(0x5af7638, 0x3ff0000000000000, 0x2)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc00087c000, 0x4fc6f38)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:584 +0x12a\npanic(0x4cdf400, 0xc00285c920)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/irisnet/irishub/app/v1/auth.AccountKeeper.DecreaseTotalLoosenToken(0x5170960, 0xc00006a580, 0x4fc6600, 0xc0000c4460, 0x517f460, 0xc0026b2360, 0xc002e19400, 0x14, 0xc003bab800, 0x2, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/auth/keeper.go:247 +0x5eb\ngithub.com/irisnet/irishub/app/v1/bank.addCoins(0x517f460, 0xc0026b2360, 0xc002e19400, 0x14, 0x5170960, 0xc00006a580, 0x4fc6600, 0xc0000c4460, 0xc0009f4ee0, 0x14, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/keeper.go:321 +0x536\ngithub.com/irisnet/irishub/app/v1/bank.sendCoins(0x517f460, 0xc0026b2360, 0xc002e19400, 0x14, 0x5170960, 0xc00006a580, 0x4fc6600, 0xc0000c4460, 0xc0009f4ea0, 0x14, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/keeper.go:336 +0x1ec\ngithub.com/irisnet/irishub/app/v1/bank.BaseKeeper.SendCoins(...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/keeper.go:96\ngithub.com/irisnet/irishub/app/v1/bank.BaseKeeper.BurnCoins(0x5170960, 0xc00006a580, 0x4fc6600, 0xc0000c4460, 0xc0000c4460, 0x517f460, 0xc0026b2360, 0xc002e19400, 0x14, 0xc0009f4ea0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/keeper.go:114 +0x1eb\ngithub.com/irisnet/irishub/app/v1/distribution/keeper.Keeper.AllocateFeeTax(0x5170960, 0xc00006a5e0, 0xc0000c4460, 0xc0000c4460, 0x5170960, 0xc00006a690, 0x51709a0, 0xc00006a6b0, 0xc000ae03c0, 0x5, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/distribution/keeper/allocation.go:120 +0x684\ngithub.com/irisnet/irishub/app/v1/gov.TaxUsageProposalExecute(0x517f460, 0xc0026b2360, 0xc002e19400, 0x14, 0x5170960, 0xc00006a650, 0xc0000c4460, 0xc0000c4460, 0x5170960, 0xc00006a690, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/execute.go:36 +0x100\ngithub.com/irisnet/irishub/app/v1/gov.Execute(0x517f460, 0xc0026b2360, 0xc002e19400, 0x14, 0x5170960, 0xc00006a650, 0xc0000c4460, 0xc0000c4460, 0x5170960, 0xc00006a690, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/execute.go:17 +0x29b\ngithub.com/irisnet/irishub/app/v1/gov.EndBlocker(0x517f460, 0xc002838ea0, 0xc002e19400, 0x12, 0x5170960, 0xc00006a650, 0xc0000c4460, 0xc0000c4460, 0x5170960, 0xc00006a690, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/handler.go:265 +0x2d2e\ngithub.com/irisnet/irishub/app/v1.(*ProtocolV1).EndBlocker(0xc00092b000, 0x517f460, 0xc002838ea0, 0xc002e19400, 0x12, 0x969, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/protocol_v1.go:347 +0xfe\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc0000ccdc0, 0x969, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:853 +0x793\ngithub.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000094ea0, 0x969, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/abci/client/local_client.go:239 +0xea\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0001a7e90, 0x969, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/proxy/app_conn.go:77 +0x51\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x51800a0, 0xc000a6e3a0, 0x518af60, 0xc0001a7e90, 0xc000941a40, 0xc003d37bf0, 0x5193700, 0xc000010008, 0xa, 0xc000a95ab0, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/state/execution.go:282 +0x69f\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000aa4000, 0x9, 0x1, 0xc000a95a90, 0xa, 0xc000a95ab0, 0x9, 0x968, 0x11, 0xc003632ce0, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/state/execution.go:104 +0x195\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc00087c000, 0x969)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1305 +0x969\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc00087c000, 0x969)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1236 +0x3e0\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc00087c000, 0x0, 0x969)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1182 +0x91\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc00087c000, 0x969, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1213 +0x61e\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc00087c000, 0xc002a552c0, 0x0, 0x0, 0xc0008a7140, 0xc0036caa00, 0xc00086fae0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1638 +0xb43\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc00087c000, 0xc002a552c0, 0x0, 0x0, 0xc000000008, 0xc00086fb90, 0x402f681)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1484 +0x5c\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc00087c000, 0x5161a00, 0xc0023e3d70, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:663 +0x6cc\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc00087c000, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:624 +0x544\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:306 +0x12b\n"

**Comment by shilei-wang** [comment]
confirm fixed
