### ISSUE TITLE
[p1] Restart irishub panic dues to exporting gateway token with an empty owner

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1744]
**To Reproduce**
Create gateway token
```
echo 1234567890 | iriscli asset create-gateway --moniker=gdex  --identity=abc --details=detail --website=website --from=v0 --chain-id=shilei-qa --fee=0.6iris --commit

echo 1234567890 | iriscli asset issue-token --family=fungible --source=gateway --gateway=gdex --symbol=g01 --symbol-at-source=source --symbol-min-alias=alias --name=name --initial-supply=10000 --from=v0 --chain-id=shilei-qa --fee=0.6iris --commit
```

Export and restart
```
iris export --for-zero-height --home=/Users/sherlock/testnet/v0/iris

iris unsafe-reset-all --home=/Users/sherlock/testnet/v0/iris

cp genesis.json /Users/sherlock/testnet/v0/iris/config

iris start --home=/Users/sherlock/testnet/v0/iris
```
------
Message: "Gateway gdex token can only be created by faa1j09jxlu0v75wc8x8vxrsdvwdvxue0hjyh68gzk, unauthorized creator faa108w3x8"

goroutine 1 [running]:
github.com/irisnet/irishub/app/v1/asset.InitGenesis(0x51b0580, 0xc0002355f0, 0xc00007abc0, 0x10, 0x51a1980, 0xc0001f9a90, 0xc0002308c0, 0x51c7b80, 0xc000235170, 0x51a1980, ...)
	/Users/sherlock/go/src/github.com/irishub/app/v1/asset/genesis.go:32 +0x58d
github.com/irisnet/irishub/app/v1.(*ProtocolV1).InitChainer(0xc0000e2900, 0x51b0580, 0xc0002355f0, 0xc00007abc0, 0x10, 0xc000a222f0, 0x1eb9e3f8, 0xed4b51957, 0x0, 0xc000a3c2b0, ...)
	/Users/sherlock/go/src/github.com/irishub/app/v1/protocol_v1.go:408 +0xded
github.com/irisnet/irishub/app.(*BaseApp).InitChain(0xc000cc20b0, 0x1eb9e3f8, 0xed4b51957, 0x0, 0xc000a3c2b0, 0x9, 0xc00007aa80, 0xc000cbb340, 0x1, 0x1, ...)
	/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:331 +0x495
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0001e9aa0, 0x1eb9e3f8, 0xed4b51957, 0x0, 0xc000a3c2b0, 0x9, 0xc00007aa80, 0xc000cbb340, 0x1, 0x1, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/abci/client/local_client.go:223 +0xe6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000069d30, 0x1eb9e3f8, 0xed4b51957, 0x0, 0xc000a3c2b0, 0x9, 0xc00007aa80, 0xc000cbb340, 0x1, 0x1, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/proxy/app_conn.go:65 +0x6b
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000902d80, 0x9, 0x1, 0x4e70225, 0x6, 0xc000a3c2b0, 0x9, 0x0, 0x0, 0x0, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/replay.go:312 +0x72d
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000902d80, 0x51c68e0, 0xc000cbbb20, 0xc0000ada40, 0x51b1140, 0xc0000a6de0)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/replay.go:269 +0x811
github.com/tendermint/tendermint/node.NewNode(0xc0000ada40, 0x51ab640, 0xc000b4c460, 0xc0001ea400, 0x51926e0, 0xc0000a7f80, 0xc0001ea640, 0x4fe9950, 0xc0001ea650, 0x51b1140, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/node/node.go:246 +0xb5c
github.com/irisnet/irishub/server.startInProcess(0xc0000a7a40, 0x4fea1c0, 0x1d, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/server/start.go:120 +0x45a
github.com/irisnet/irishub/server.StartCmd.func1(0xc000233b00, 0xc00009cbb0, 0x0, 0x1, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/server/start.go:41 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000233b00, 0xc00009cb90, 0x1, 0x1, 0xc000233b00, 0xc00009cb90)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0xc000232fc0, 0x2, 0xc0000a7ce0, 0x4e943de)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000232fc0, 0x4fea5d0, 0x4, 0xc000a0a0a0)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/sherlock/go/src/github.com/irishub/cmd/iris/main.go:79 +0x5f3

**Comment by shilei-wang** [comment]
confirm fixed
