### ISSUE TITLE
[p1] Coin set Panic caused by sending liquidity without "-min"

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1916]
**To Reproduce**
step 1. create a gateway (g123)
step 2. issue a gateway token (g123.t123)
step 3. CoinswapUtils.deposit("10 iris", "10 g123.t123") //  get "10 u-g123.t123-min" liquidities back
step 4. send "1u-g123.t123-min" liquidity to other account , works ok.
step 5. send "1u-g123.t123" liquidity to other account , occurs Panic.

-----
```
echo 1234567890 | iriscli bank send --amount=1u-g123.t123 --fee=0.004iris --commit --chain-id=shilei-qa --from=v0 --to=faa1lcuw6ewd2gfxap37sejewmta205sgssmv5fnju
```

```
panic: invalid coin set: 1u-g123.t123 [recovered]
	panic: invalid coin set: 1u-g123.t123

goroutine 1 [running]:
main.main.func1()
	/Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:48 +0xb3
panic(0x4ac8d00, 0xc0001874d0)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/irisnet/irishub/types.NewCoins(0xc0008627c0, 0x1, 0x1, 0x0, 0x1, 0xc0008627c0)
	/Users/sherlock/go/src/github.com/irishub/types/coin.go:141 +0x20a
github.com/irisnet/irishub/client/context.CLIContext.ParseCoins(0xc00011d490, 0xc000186c60, 0x4efe120, 0xc000a351a0, 0x4ecb840, 0xc0000c2000, 0x4c0d44b, 0x4, 0x0, 0x4c1e029, ...)
	/Users/sherlock/go/src/github.com/irishub/client/context/context.go:332 +0x298
github.com/irisnet/irishub/client/bank/cli.SendTxCmd.func1(0xc000975b00, 0xc00008b2c0, 0x0, 0x6, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/client/bank/cli/sendtx.go:44 +0x347
github.com/spf13/cobra.(*Command).execute(0xc000975b00, 0xc00008b140, 0x6, 0x6, 0xc000975b00, 0xc00008b140)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0x56f2520, 0xc0008137c0, 0x0, 0x0)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x56f2520, 0x4d879a8, 0x0, 0xc0009accc0)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:325 +0x20ec
```

**Comment by shilei-wang** [comment]
confirm fixed
