### ISSUE TITLE
[p2] "invalid coin denominations" was observed under specific use cases

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1963]
It seems we have a lot of problems in "export" use case.
This bug happens when user try send "Liquidity" to BurnedCoinsAccAddr(faa108a0ts008fphurftmsvj5p2q8ltq8qeduq57d6), and only happens after "export" and "restart".

**To Reproduce**
1. symbol_1 = AssetUtils.issueToken(v0)
2. CoinswapUtils.deposit(v0, symbol_1, 100, 100)
3. BankUtils.send(v0, "faa108a0ts008fphurftmsvj5p2q8ltq8qeduq57d6","1u-symbol_1-min")
--
4. shut up the chain / export genesis / unsafe reset / restart chain
--
5. symbol_2 = AssetUtils.issueToken(v0)
6. CoinswapUtils.deposit(v0, symbol_2, 100, 100)
7. BankUtils.send(v0, "faa108a0ts008fphurftmsvj5p2q8ltq8qeduq57d6","1u-symbol_2-min")

```
ERROR: {"codespace":"sdk","code":1,"message":"recovered: invalid coin denominations; u-t251225-min, u-t734317-min\nstack:\ngoroutine 16 [running]:\nruntime/debug.Stack(0xc00232e918, 0x4cec300, 0xc003464910)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/irisnet/irishub/app.(*BaseApp).runTx.func1(0xc00232fa28, 0xc00232f800, 0xc00232f778)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:758 +0x93\npanic(0x4cec300, 0xc003464910)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/irisnet/irishub/types.Coin.Sub(0xc003189bd0, 0xd, 0xc00346ae80, 0xc003188780, 0xd, 0xc0032d69a0, 0xc0031044c0, 0x1c, 0xc003188780)\n\t/Users/sherlock/go/src/github.com/irishub/types/coin.go:104 +0x19e\ngithub.com/irisnet/irishub/app/v1/auth.AccountKeeper.DecreaseTotalSupply(0x51f7d80, 0xc0001d9060, 0x5029e20, 0xc0000d5180, 0x5206c80, 0xc0032ddd40, 0xc0031044c0, 0x1c, 0xc003188780, 0xd, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/auth/keeper.go:309 +0x1a4\ngithub.com/irisnet/irishub/app/v1/bank.addCoins(0x5206c80, 0xc0032ddd40, 0xc0031044c0, 0x1c, 0x51f7d80, 0xc0001d9060, 0x5029e20, 0xc0000d5180, 0xc003184d60, 0x14, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/keeper.go:374 +0x420\ngithub.com/irisnet/irishub/app/v1/bank.inputOutputCoins(0x5206c80, 0xc0032ddd40, 0xc0031044c0, 0x1c, 0x51f7d80, 0xc0001d9060, 0x5029e20, 0xc0000d5180, 0xc003187860, 0x1, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/keeper.go:438 +0x477\ngithub.com/irisnet/irishub/app/v1/bank.BaseKeeper.InputOutputCoins(...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/keeper.go:161\ngithub.com/irisnet/irishub/app/v1/bank.handleMsgSend(0x5206c80, 0xc0032ddd40, 0xc0031044c0, 0x1c, 0x52200c0, 0xc0009e70b0, 0xc003187860, 0x1, 0x1, 0xc003187920, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/handler.go:28 +0xe9\ngithub.com/irisnet/irishub/app/v1/bank.NewHandler.func1(0x5206c80, 0xc0032ddd40, 0xc0031044c0, 0x1c, 0x520af00, 0xc003187950, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/bank/handler.go:12 +0x357\ngithub.com/irisnet/irishub/app.(*BaseApp).runMsgs(0xc0000daf20, 0x5206c80, 0xc0032ddcb0, 0xc0031044c0, 0x1b, 0xc00254f810, 0x1, 0x1, 0x5206c02, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:643 +0x1143\ngithub.com/irisnet/irishub/app.(*BaseApp).runTx(0xc0000daf20, 0x2, 0xc002b9b100, 0xf9, 0xf9, 0x51f9d40, 0xc0032d51a0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:867 +0xa46\ngithub.com/irisnet/irishub/app.(*BaseApp).DeliverTx(0xc0000daf20, 0xc002b9b100, 0xf9, 0xf9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:570 +0x286\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc0000b7920, 0xc002b9b100, 0xf9, 0xf9, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/abci/client/local_client.go:88 +0xc5\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc000aa1170, 0xc002b9b100, 0xf9, 0xf9, 0x9)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/proxy/app_conn.go:73 +0x51\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x5207840, 0xc000bb37a0, 0x5213380, 0xc000aa1170, 0xc00289cf00, 0xc0031012c0, 0x521b940, 0xc0000b41b0, 0x6, 0xc000ba4180, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/state/execution.go:275 +0x5e2\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0001ec700, 0x9, 0x2, 0xc000ba4166, 0x6, 0xc000ba4180, 0x9, 0x9d, 0x4, 0xc000906040, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/state/execution.go:104 +0x195\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000a91500, 0x9e)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1331 +0x969\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000a91500, 0x9e)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1262 +0x3e0\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000a91500, 0x0, 0x9e)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1208 +0x91\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000a91500, 0x9e, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1239 +0x61e\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000a91500, 0xc003472960, 0x0, 0x0, 0xc0024627e0, 0xc002c16f00, 0xc003e19ae0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1664 +0xb43\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000a91500, 0xc003472960, 0x0, 0x0, 0xc000000008, 0xc003e19b90, 0x402f0e1)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1510 +0x5c\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000a91500, 0x51e84c0, 0xc002753850, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:689 +0x6cc\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000a91500, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:650 +0x55d\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:322 +0x13a\n"}
```

**Comment by shilei-wang** [comment]
confirm fixed
