### ISSUE TITLE
[p2] "panic recovered: interface conversion" was observed after submitting a upgrade proposal in rest api

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1964]
**To Reproduce**
generate->sign->broadcast: POST /gov/proposals Submit a proposal

GovUtils.submitProposalWithParams(v0,"proposer:"+v0_faa, "version:2" ,"proposal_type:SoftwareUpgrade", "initial_deposit:1200iris","switch-height:50000000", "software:t","title:title","description:description")

> -------

{"codespace":"sdk","code":1,"message":"recovered: interface conversion: gov.Content is gov.MsgSubmitProposal, not gov.MsgSubmitSoftwareUpgradeProposal\nstack:\ngoroutine 82 [running]:\nruntime/debug.Stack(0xc000aef5a8, 0x4d5d360, 0xc0035c0600)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/irisnet/irishub/app.(*BaseApp).runTx.func1(0xc000af1a28, 0xc000af1800, 0xc000af1778)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:758 +0x93\npanic(0x4d5d360, 0xc0035c0600)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/irisnet/irishub/app/v1/gov.createSoftwareUpgradeInfo.func1.1(0x0, 0xc002d82b35, 0x5, 0xc002d82b50, 0xb, 0x102, 0xc002df61c0, 0xc002df61e0, 0xc002df6200, 0xc002df6220, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/proposal_util.go:47 +0x227\ngithub.com/irisnet/irishub/app/v1/gov.buildProposal(0x96ae7a8, 0xc000224690, 0x5029eb8, 0xc0000dcb40, 0xffffffffffffffff)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/proposal_util.go:128 +0x28d\ngithub.com/irisnet/irishub/app/v1/gov.createSoftwareUpgradeInfo.func1(0x96ae7a8, 0xc000224690, 0x4eb8917, 0xf)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/proposal_util.go:46 +0x41\ngithub.com/irisnet/irishub/app/v1/gov.ProposalKind.NewProposal(0xc000224602, 0x96ae7a8, 0xc000224690, 0x96ae7a8, 0xc000224690, 0x4e82c40, 0xc002dbf8d0)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/proposals.go:293 +0x86\ngithub.com/irisnet/irishub/app/v1/gov.Keeper.SubmitProposal(0x51f7d80, 0xc0001d6970, 0xc000221a40, 0xc000221a40, 0x51f7d80, 0xc0001d6990, 0x51f7dc0, 0xc0001d69a0, 0xc000a7e4c0, 0x3, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/keeper.go:90 +0xa7\ngithub.com/irisnet/irishub/app/v1/gov.handleMsgSubmitProposal(0x5206c80, 0xc0035c05d0, 0xc002e55640, 0x1c, 0x51f7d80, 0xc0001d6970, 0xc000221a40, 0xc000221a40, 0x51f7d80, 0xc0001d6990, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/handler.go:31 +0xe1\ngithub.com/irisnet/irishub/app/v1/gov.NewHandler.func1(0x5206c80, 0xc0035c05d0, 0xc002e55640, 0x1c, 0x520b100, 0xc000224690, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/gov/handler.go:18 +0x137\ngithub.com/irisnet/irishub/app.(*BaseApp).runMsgs(0xc00018a2c0, 0x5206c80, 0xc0035c0540, 0xc002e55640, 0x1b, 0xc003f38af0, 0x1, 0x1, 0x5206c02, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:643 +0x1143\ngithub.com/irisnet/irishub/app.(*BaseApp).runTx(0xc00018a2c0, 0x2, 0xc002ac9d00, 0xf6, 0xf6, 0x51f9d40, 0xc002dbd8c0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:867 +0xa46\ngithub.com/irisnet/irishub/app.(*BaseApp).DeliverTx(0xc00018a2c0, 0xc002ac9d00, 0xf6, 0xf6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:570 +0x286\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc0001d4d80, 0xc002ac9d00, 0xf6, 0xf6, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/abci/client/local_client.go:88 +0xc5\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc000992bd0, 0xc002ac9d00, 0xf6, 0xf6, 0x9)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/proxy/app_conn.go:73 +0x51\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x5207840, 0xc000775880, 0x5213380, 0xc000992bd0, 0xc002a414a0, 0xc002920900, 0x521b940, 0xc0000d80f0, 0x6, 0xc000991710, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/state/execution.go:275 +0x5e2\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000220700, 0x9, 0x2, 0xc0009916e6, 0x6, 0xc000991710, 0x9, 0x47a, 0x2, 0xc0039c1900, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/state/execution.go:104 +0x195\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc0009b9180, 0x47b)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1331 +0x969\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc0009b9180, 0x47b)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1262 +0x3e0\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc0009b9180, 0x0, 0x47b)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1208 +0x91\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc0009b9180, 0x47b, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1239 +0x61e\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc0009b9180, 0xc002ba2f00, 0x0, 0x0, 0xc0029918c0, 0xc000803a00, 0xc000af3ae0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1664 +0xb43\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc0009b9180, 0xc002ba2f00, 0x0, 0x0, 0xc000000008, 0xc000af3b90, 0x402f0e1)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:1510 +0x5c\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc0009b9180, 0x51e84c0, 0xc0001cf0a8, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:689 +0x6cc\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc0009b9180, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:650 +0x55d\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/consensus/state.go:322 +0x13a\n"}

**Comment by shilei-wang** [comment]
not fixed
