### ISSUE TITLE
[p1] "panic: invalid coin set" is observed when trying to send tokens with "iris-micro" unit

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1969]
**Describe the bug**
This bug only reproduced in 16.0, it not exist in 15.0

**To Reproduce**
```
echo 1234567890 | iriscli bank send --amount=11000000iris-micro --fee=0.004iris --commit --chain-id=shilei-qa --from=v0 --to=faa1lcuw6ewd2gfxap37sejewmta205sgssmv5fnju
```
------
panic: invalid coin set: 11000000iris-micro [recovered]
  panic: invalid coin set: 11000000iris-micro

goroutine 1 [running]:
main.main.func1()
  /Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:48 +0xb3
panic(0x4aba3c0, 0xc0001811a0)
  /usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/irisnet/irishub/types.NewCoins(0xc0001ab7c0, 0x1, 0x1, 0x0, 0x1, 0xc0001ab7c0)
  /Users/sherlock/go/src/github.com/irishub/types/coin.go:141 +0x20a
github.com/irisnet/irishub/client/context.CLIContext.ParseCoins(0xc0001f4fc0, 0xc000180fa0, 0x4eed6a0, 0xc0001ab740, 0x4ebb440, 0xc0000b6000, 0x4bfd2e6, 0x4, 0x0, 0x4c0df58, ...)
  /Users/sherlock/go/src/github.com/irishub/client/context/context.go:335 +0x298
github.com/irisnet/irishub/client/bank/cli.SendTxCmd.func1(0xc000afc000, 0xc000095a40, 0x0, 0x6, 0x0, 0x0)
  /Users/sherlock/go/src/github.com/irishub/client/bank/cli/sendtx.go:44 +0x347
github.com/spf13/cobra.(*Command).execute(0xc000afc000, 0xc000095920, 0x6, 0x6, 0xc000afc000, 0xc000095920)
  /Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0x56da600, 0xc000b5c320, 0x0, 0x0)
  /Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
  /Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x56da600, 0x4d78618, 0x0, 0xc000914060)
  /Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/libs/cli/setup.go:89 +0x3c
main.main()
  /Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:325 +0x20ec

**Comment by shilei-wang** [comment]
confirm fixed
