### ISSUE TITLE
[p1] Trying to reset the node, which restarted from a snapshot data, will corrupt data file and return panic runtime error.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2045]
Which should be noticed is once the data file is corrupted, it can't be recovered.

**To Reproduce**
```
iris snapshot --home=/Users/sherlock/testnet/v0/iris
rm -rf /Users/sherlock/testnet/v0/iris/data
mv /Users/sherlock/testnet/v0/iris/data.bak /Users/sherlock/testnet/v0/iris/data
iris start --home=/Users/sherlock/testnet/v0/iris
iris reset --height=100 --home=/Users/sherlock/testnet/v0/iris
```
----
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47210a2]

goroutine 28 [running]:
github.com/tendermint/tendermint/state.NewABCIResponses(...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/state/store.go:125
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x5284180, 0xc000846300, 0x52902a0, 0xc00095e970, 0x0, 0xc000be45d0, 0x5298de0, 0xc0001e4020, 0xc000821cc8, 0x42f180e, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/state/execution.go:235 +0x92
github.com/tendermint/tendermint/state.ExecCommitBlock(0x52902a0, 0xc00095e970, 0x0, 0x5284180, 0xc000846300, 0xc000be45d0, 0x5298de0, 0xc0001e4020, 0x11, 0x733d656c75646f6d, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/state/execution.go:546 +0x9b
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc000ac4300, 0x9, 0x2, 0xc000efa410, 0xa, 0xc000efa430, 0x9, 0x6b5, 0xee, 0xc000970040, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/consensus/replay.go:432 +0x2fa
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000ac4300, 0x9, 0x2, 0xc000efa410, 0xa, 0xc000efa430, 0x9, 0x6b5, 0xee, 0xc000970040, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/consensus/replay.go:361 +0x98a
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000ac4300, 0x529af60, 0xc0000d1490, 0xc000874280, 0x5284180, 0xc00110de00)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/consensus/replay.go:265 +0x811
github.com/tendermint/tendermint/node.NewNode(0xc000874280, 0x527e100, 0xc0001cfa40, 0xc0001b98a0, 0x5264b20, 0xc000d78180, 0xc00089fdf0, 0x503cba8, 0xc00089fe00, 0x5284180, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190905014850-7daf474ce5c0/node/node.go:245 +0xb5c
main.startNodeAndReplay.func1(0xc0009cc420)
	/Users/sherlock/go/src/github.com/irishub/cmd/iris/main.go:142 +0x2f3
created by main.startNodeAndReplay
	/Users/sherlock/go/src/github.com/irishub/cmd/iris/main.go:157 +0x22e

**Comment by shilei-wang** [comment]
confirm fixed
