### ISSUE TITLE
[p2]Create htlc with un-exist token returns Panic error message.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2054]
**Describe the bug**
Create htlc with un-exist token returns Panic error message.

**To Reproduce**
echo 1234567890 | iriscli htlc create --from=v0 --to=faa1lcuw6ewd2gfxap37sejewmta205sgssmv5fnju  --amount=10iris,10g237432.t88489 --time-lock=5 --timestamp=1580000000 --receiver-on-other-chain=00 --fee=0.3iris --chain-id=shilei-qa --commit

---
goroutine 1 [running]:
main.main.func1()
	/Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:49 +0xb3
panic(0x4ac3f60, 0xc0000a15f0)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/irisnet/irishub/types.NewCoins(0xc000aa25a0, 0x1, 0x1, 0x0, 0x1, 0xc000aa25a0)
	/Users/sherlock/go/src/github.com/irishub/types/coin.go:141 +0x20a
github.com/irisnet/irishub/client/context.CLIContext.ParseCoins(0xc000200620, 0xc0000cb450, 0x4f0b0c0, 0xc00000e960, 0x4ed8aa0, 0xc0000c0000, 0x4c08c8a, 0x4, 0x0, 0x4c199d5, ...)
	/Users/sherlock/go/src/github.com/irishub/client/context/context.go:338 +0x298
github.com/irisnet/irishub/client/bank/cli.SendTxCmd.func1(0xc000924480, 0xc0000c33e0, 0x0, 0x6, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/client/bank/cli/sendtx.go:44 +0x347
github.com/spf13/cobra.(*Command).execute(0xc000924480, 0xc0000c32c0, 0x6, 0x6, 0xc000924480, 0xc0000c32c0)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0x5701660, 0xc0009774a0, 0x0, 0x0)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x5701660, 0x4d84b30, 0x0, 0xc000a380e0)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.28.1-0.20191030084935-cc25237a944f/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:347 +0x22f2

**Comment by shilei-wang** [comment]
confirm fixed
