### ISSUE TITLE
Cannot snapshot from catching_up node

### ISSUE THREAD

**Issue by chengwenxi** [irisnet/irishub#2063]
### Summary
The catching_up node's `cs.wal` file is empty.

**error message**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4717605]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
	/usr/local/Cellar/go/1.13.1/libexec/src/sync/mutex.go:74
github.com/tendermint/tendermint/libs/autofile.(*GroupReader).Close(0x0, 0x0, 0x0)
	/Users/bianjie/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/libs/autofile/group.go:595 +0x35
github.com/irisnet/irishub/server.snapshotCsWAL(0xc0000373c0, 0x19, 0xc0000373e0, 0x1d, 0x3fe0, 0x5256360, 0xc000cf61a0)
	/Users/bianjie/github.com/irisnet/irishub/server/snapshot.go:148 +0x542
github.com/irisnet/irishub/server.dumpData(0xc0000373c0, 0x19, 0xc0000373e0, 0x1d, 0xc0000e8000, 0x2, 0xc000877be8)
	/Users/bianjie/github.com/irisnet/irishub/server/snapshot.go:71 +0xa9
github.com/irisnet/irishub/server.SnapshotCmd.func1(0xc0001bf200, 0xc000cffc40, 0x0, 0x2, 0x0, 0x0)
	/Users/bianjie/github.com/irisnet/irishub/server/snapshot.go:45 +0x20d
github.com/spf13/cobra.(*Command).execute(0xc0001bf200, 0xc000cffbe0, 0x2, 0x2, 0xc0001bf200, 0xc000cffbe0)
	/Users/bianjie/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x42c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000185200, 0x2, 0xc000cffb40, 0x4ee0a10)
	/Users/bianjie/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2c9
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/bianjie/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000185200, 0x503b5f8, 0x4, 0xc000c1c0c0)
	/Users/bianjie/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/bianjie/github.com/irisnet/irishub/cmd/iris/main.go:80 +0x62c
```

**Comment by shilei-wang** [comment]
confirm fixed
