### ISSUE TITLE
[p1] Failed to load block and panic after snapshot.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2070]
**Describe the bug**
Loading block data from a snapshot node causes Panic

----
I[2019-11-11|11:46:10.586] Committed state                              module=state height=923 txs=0 appHash=298D921ED2497491A36AFB72C124967451B3CCB85CFAAF03BDC95BD69D2D242E
panic: Panicked on a Crisis: Failed to load block 896 when blockStore is at 923

goroutine 1486 [running]:
github.com/tendermint/tendermint/libs/common.PanicCrisis(...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/libs/common/errors.go:232
github.com/tendermint/tendermint/consensus.(*ConsensusReactor).gossipDataRoutine(0xc000181700, 0x52a64e0, 0xc000c49980, 0xc0010f9a00)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/consensus/reactor.go:508 +0xeb8
created by github.com/tendermint/tendermint/consensus.(*ConsensusReactor).AddPeer
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/consensus/reactor.go:183 +0xcc

**Comment by shilei-wang** [comment]
confirm fixed
