### ISSUE TITLE
[p2] Snapshot an "unsafe-reset-all" node causes Panic (especially while catching up)

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2076]
**Describe the bug**
It seems the problem is caused by the flag "stateHeight"

**To Reproduce**
go run /Users/sherlock/go/src/github.com/irishub_auto/autotest-cmd/autoStart/lanchIris.go c 2
iris start --home=/Users/sherlock/testnet/v0/iris
iris start --home=/Users/sherlock/testnet/v1/iris
iriscli stake validators
echo 1234567890 | iriscli stake delegate --address-validator=fva1xskuyaq0e993nye76uwdrl27xe7dpl8dkxzj2x --amount=500iris --fee=0.004iris --commit  --from=v0  --chain-id=shilei-qa

iris unsafe-reset-all --home=/Users/sherlock/testnet/v0/iris
iris start --home=/Users/sherlock/testnet/v0/iris

iris snapshot --home=/Users/sherlock/testnet/v0/iris
rm -rf /Users/sherlock/testnet/v0/iris/data
mv /Users/sherlock/testnet/v0/iris/data.bak /Users/sherlock/testnet/v0/iris/data

iris start --home=/Users/sherlock/testnet/v0/iris

---
I[2019-11-12|18:00:49.707] Starting ABCI with Tendermint                module=main 
I[2019-11-12|18:00:49.820] ABCI Replay Blocks                           module=state appHeight=91 storeHeight=92 **stateHeight=0**
panic: Panicked on a Sanity Check: StoreBlockHeight (92) > StateBlockHeight + 1 (1)

goroutine 1 [running]:
github.com/tendermint/tendermint/libs/common.PanicSanity(...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20191111091141-eb62cce94c30/libs/common/errors.go:224
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000223200, 0x9, 0x2, 0x4ec1e30, 0x6, 0xc0001da610, 0x9, 0x0, 0x0, 0x0, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20191111091141-eb62cce94c30/consensus/replay.go:350 +0x154e
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000223200, 0x529d3a0, 0xc000116230, 0xc000130f00, 0x5286540, 0xc00088e160)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20191111091141-eb62cce94c30/consensus/replay.go:265 +0x811
github.com/tendermint/tendermint/node.NewNode(0xc000130f00, 0x5280440, 0xc000129900, 0xc0001af170, 0x5266ea0, 0xc000018c20, 0xc000aadab0, 0x503f048, 0xc000aadac0, 0x5286540, ...)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20191111091141-eb62cce94c30/node/node.go:245 +0xb5c
github.com/irisnet/irishub/server.startInProcess(0xc000a711a0, 0x503f900, 0x1d, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/server/start.go:120 +0x45a
github.com/irisnet/irishub/server.StartCmd.func1(0xc000aae000, 0xc000aac7f0, 0x0, 0x1, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/server/start.go:41 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000aae000, 0xc000aac7d0, 0x1, 0x1, 0xc000aae000, 0xc000aac7d0)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a79440, 0x2, 0xc000a71440, 0x4ee7535)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000a79440, 0x503fd10, 0x4, 0xc0009fa700)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20191111091141-eb62cce94c30/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/sherlock/go/src/github.com/irishub/cmd/iris/main.go:80 +0x62d

**Comment by shilei-wang** [comment]
confirm fixed
