### ISSUE TITLE
[p3] Query upgrade info returns Panic message.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2158]
**Describe the bug**
Terminate iris first and query upgrade info.

iriscli upgrade info --trust-node
panic: UnmarshalBinaryLengthPrefixed cannot decode empty bytes [recovered]
	panic: UnmarshalBinaryLengthPrefixed cannot decode empty bytes

goroutine 1 [running]:
main.main.func1()
	/Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:49 +0xb3
panic(0x4ac4080, 0xc000bac000)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/go-amino.(*Codec).MustUnmarshalBinaryLengthPrefixed(...)
	/Users/sherlock/go/pkg/mod/github.com/tendermint/go-amino@v0.14.1/amino.go:316
github.com/irisnet/irishub/client/upgrade/cli.GetInfoCmd.func1(0xc000b17b00, 0xc000a34140, 0x0, 0x1, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/client/upgrade/cli/query.go:36 +0xafc
github.com/spf13/cobra.(*Command).execute(0xc000b17b00, 0xc000a34120, 0x1, 0x1, 0xc000b17b00, 0xc000a34120)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0x5700680, 0xc000b606e0, 0x0, 0x0)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x5700680, 0x4d84da0, 0x0, 0xc000883100)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.1/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/sherlock/go/src/github.com/irishub/cmd/iriscli/main.go:347 +0x22f2

**Comment by shilei-wang** [comment]
confirm  fixed
