### ISSUE TITLE
The latest asset refactor causes "CONSENSUS FAILURE" after software-upgrade

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2310]
**Describe the bug**
CONSENSUS FAILURE  after software-upgrade from v16 to latest v17

**To Reproduce**

E[2020-03-24|17:40:49.441] CONSENSUS FAILURE!!!                         module=consensus err="interface conversion: interface is nil, not types.KVStore" stack="goroutine 92 [running]:\nruntime/debug.Stack(0x5d73b98, 0x3ff0000000000000, 0x2)\n\t/usr/local/Cellar/go/1.13.6/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc00087c380, 0x5185138)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:601 +0x129\npanic(0x4e76ae0, 0xc002fd7710)\n\t/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2\ngithub.com/irisnet/irishub/store.cacheMultiStore.GetKVStore(...)\n\t/Users/sherlock/go/src/github.com/irishub/store/cachemultistore.go:133\ngithub.com/irisnet/irishub/types.Context.KVStore(0x540b1c0, 0xc0000ce008, 0x541fe60, 0xc002de38c0, 0x9, 0x3, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/types/context.go:218 +0x89\ngithub.com/irisnet/irishub/app/v3/asset/internal/keeper.Keeper.deleteTotalSupplies(0x53fc3c0, 0xc0001c1bc0, 0xc00016ea10, 0x7c58fb0, 0xc002fd68a0, 0x53ebf40, 0xc002fd70e0, 0x4ffe326, 0x5, 0xc00016ea10, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v3/asset/internal/keeper/upgrade.go:98 +0x73\ngithub.com/irisnet/irishub/app/v3/asset/internal/keeper.Keeper.Init(0x53fc3c0, 0xc0001c1bc0, 0xc00016ea10, 0x7c58fb0, 0xc002fd68a0, 0x53ebf40, 0xc002fd70e0, 0x4ffe326, 0x5, 0xc00016ea10, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v3/asset/internal/keeper/upgrade.go:52 +0x665\ngithub.com/irisnet/irishub/app/v3.(*ProtocolV3).Init(0xc00089f500, 0x540b1c0, 0xc0000ce008, 0x541fe60, 0xc002de38c0, 0x9, 0x3, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v3/protocol_v3.go:109 +0xac\ngithub.com/irisnet/irishub/app/protocol.(*ProtocolEngine).Activate(0xc0002d1bf0, 0x3, 0x540b1c0, 0xc0000ce008, 0x541fe60, 0xc002de38c0, 0x9, 0x3, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/protocol/engine.go:51 +0xe9\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc0000eef20, 0x63, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:907 +0x214\ngithub.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0009d6cc0, 0x63, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/abci/client/local_client.go:239 +0x108\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0008a84d0, 0x63, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/proxy/app_conn.go:77 +0x51\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x540be00, 0xc0008bcba0, 0x5419060, 0xc0008a84d0, 0xc0025bad20, 0xc002f6a3c0, 0x5422560, 0xc0001ca338, 0x6, 0xc0009f22e0, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/state/execution.go:281 +0x67a\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000154e70, 0x9, 0x3, 0xc0009f22b6, 0x6, 0xc0009f22e0, 0x9, 0x62, 0x2, 0xc002e457c0, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/state/execution.go:103 +0x190\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc00087c380, 0x63)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:1337 +0x952\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc00087c380, 0x63)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:1265 +0x383\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc00087c380, 0x0, 0x63)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:1211 +0x90\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc00087c380, 0x63, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:1242 +0x61a\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc00087c380, 0xc002363720, 0x0, 0x0, 0xc000c35ab0, 0xc002df6300, 0x10d)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:1670 +0xa7b\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc00087c380, 0xc002363720, 0x0, 0x0, 0x0, 0xc000c35af0, 0x4031491)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:1516 +0x59\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc00087c380, 0x53eaac0, 0xc00361eee0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:692 +0x5fd\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc00087c380, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:653 +0x587\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.2-0.20200312080607-e72160dff3eb/consensus/state.go:322 +0x13a\n"

**Comment by shilei-wang** [comment]
fixed
