### ISSUE TITLE
panic when iris start new node for version 1.1.0  with now mainnet irishub-1 genesis.json

### ISSUE THREAD

**Issue by jingniao** [irisnet/irishub#2609]
go version 1.16.2
iris version 1.1.0
generic.json version irishub-1
join mainnet use doc [get-started](https://github.com/irisnet/irishub/blob/v1.1.0/docs/get-started/mainnet.md)

```log
3:05PM INF asserting crisis invariants inv=5/11 module=x/crisis name=staking/nonnegative-power
3:05PM INF asserting crisis invariants inv=6/11 module=x/crisis name=staking/positive-delegation
3:05PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/delegator-shares
3:05PM INF asserting crisis invariants inv=8/11 module=x/crisis name=bank/nonnegative-outstanding
3:05PM INF asserting crisis invariants inv=9/11 module=x/crisis name=bank/total-supply
3:05PM INF asserting crisis invariants inv=10/11 module=x/crisis name=gov/module-account
3:05PM INF asserted all invariants duration=14348.049701 height=9146456 module=x/crisis
3:05PM INF created new capability module=ibc name=ports/transfer
3:05PM INF port binded module=x/ibc/port port=transfer
3:05PM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: unknown field "pending_htlcs" in types.GenesisState

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0004a2510, 0xc0012fc540, 0x14, 0x18, 0x24923d0, 0xc00794f440)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/codec/proto_codec.go:160 +0x98
github.com/irisnet/irismod/modules/htlc.AppModule.InitGenesis(0x24bddf8, 0xc0004a2510, 0x2481a68, 0xc001382d00, 0x24bddf8, 0xc0004a2510, 0x24b7318, 0xc0004a2510, 0xc000578058, 0x2481a68, ...)
        /root/go/pkg/mod/github.com/irisnet/irismod@v1.4.0/modules/htlc/module.go:138 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc0004b9570, 0x249f2c8, 0xc000052040, 0x24b6c50, 0xc000099280, 0x0, 0x0, 0xc0004aa280, 0x9, 0x8b9058, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/types/module/module.go:304 +0x2b5
github.com/irisnet/irishub/app.(*IrisApp).InitChainer(0xc0002bac00, 0x249f2c8, 0xc000052040, 0x24b6c50, 0xc000099280, 0x0, 0x0, 0xc0004aa280, 0x9, 0x8b9058, ...)
        /root/irishub/app/app.go:646 +0x5d0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0000bc340, 0x0, 0xed40aba58, 0x0, 0xc0004aa280, 0x9, 0xc0000d42e0, 0x3463a88, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/baseapp/abci.go:62 +0x2f5
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000526a80, 0x0, 0xed40aba58, 0x0, 0xc0004aa280, 0x9, 0xc0000d42e0, 0x3463a88, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000e854a0, 0x0, 0xed40aba58, 0x0, 0xc0004aa280, 0x9, 0xc0000d42e0, 0x3463a88, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc00111c498, 0xb, 0x0, 0x0, 0x0, 0xc0004aa280, 0x9, 0x8b9058, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00111c498, 0x24bb238, 0xc0001565b0, 0x1, 0x0)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x24b6e58, 0xc000e85350, 0xb, 0x0, 0x0, 0x0, 0xc0004aa280, 0x9, 0x8b9058, 0x0, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/node/node.go:277 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000ff8c80, 0x2496510, 0xc0000c45a0, 0xc000e84000, 0x245e2c0, 0xc000f423d8, 0xc000e840a0, 0x2240c58, 0xc000e841c0, 0x249ffb0, ...)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.8/node/node.go:685 +0x1e65
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00105f2a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24a8dd0, 0xc000fd6510, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:244 +0x585
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001029b80, 0xc0010dbd30, 0x0, 0x1, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:120 +0x1c8
github.com/spf13/cobra.(*Command).execute(0xc001029b80, 0xc0010dbd20, 0x1, 0x1, 0xc001029b80, 0xc0010dbd20)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f6ab00, 0x0, 0x0, 0xc000f79820)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000f6ab00, 0xc000f79820, 0xb, 0x24bddf8, 0xc000fd6510)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/server/cmd/execute.go:36 +0x265
main.main()
        /root/irishub/cmd/iris/main.go:17 +0x45
```

**Comment by chengwenxi** [comment]
@jingniao thanks for your report. We update the get start docs, plz have a try.

**Comment by jingniao** [comment]
sync is ok
