### ISSUE TITLE
panic: unknown field "pending_htlcs" in types.GenesisState

### ISSUE THREAD

**Issue by Xiechengqi** [irisnet/irishub#2639]
**Describe the bug**
os: Ubuntu18.04
iris: v1.1.1
go: 1.16.6

```
# iris start --home=/data/iris-node-1.1.1/data
8:43AM INF starting ABCI with Tendermint
8:43AM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:43AM INF Starting localClient service connection=query impl=localClient module=abci-client
8:43AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:43AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:43AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:43AM INF Starting EventBus service impl=EventBus module=events
8:43AM INF Starting PubSub service impl=PubSub module=pubsub
8:43AM INF Starting IndexerService service impl=IndexerService module=txindex
8:43AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
8:43AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
8:43AM INF asserting crisis invariants inv=0/11 module=x/crisis name=distribution/nonnegative-outstanding
8:43AM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/can-withdraw
8:43AM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/reference-count
8:43AM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/module-account
8:43AM INF asserting crisis invariants inv=4/11 module=x/crisis name=bank/nonnegative-outstanding
8:43AM INF asserting crisis invariants inv=5/11 module=x/crisis name=bank/total-supply
8:43AM INF asserting crisis invariants inv=6/11 module=x/crisis name=gov/module-account
8:43AM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
8:43AM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
8:43AM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
8:43AM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
8:43AM INF asserted all invariants duration=5442.016416 height=9146456 module=x/crisis
8:43AM INF created new capability module=ibc name=ports/transfer
8:43AM INF port binded module=x/ibc/port port=transfer
8:43AM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: unknown field "pending_htlcs" in types.GenesisState

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0000fe660, 0xc0010929f0, 0x14, 0x18, 0x24a1630, 0xc0074ad920)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/codec/proto_codec.go:160 +0x98
github.com/irisnet/irismod/modules/htlc.AppModule.InitGenesis(0x24cd2f8, 0xc0000fe660, 0x2490d08, 0xc00014dc10, 0x24cd2f8, 0xc0000fe660, 0x24c6798, 0xc0000fe660, 0xc000d6a018, 0x2490d08, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/irisnet/irismod@v1.4.0/modules/htlc/module.go:138 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000d816c0, 0x24ae608, 0xc0000580b0, 0x24c60d0, 0xc000569040, 0x0, 0x0, 0xc0004ca470, 0x9, 0x8b9058, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/types/module/module.go:304 +0x2b5
github.com/irisnet/irishub/app.(*IrisApp).InitChainer(0xc000bcec00, 0x24ae608, 0xc0000580b0, 0x24c60d0, 0xc000569040, 0x0, 0x0, 0xc0004ca470, 0x9, 0x8b9058, ...)
	/data/iris-node-1.1.1/src/app/app.go:646 +0x5d0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000b71380, 0x0, 0xed40aba58, 0x0, 0xc0004ca470, 0x9, 0xc000c2f5a0, 0x3480c88, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:62 +0x2f5
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000ca0cc0, 0x0, 0xed40aba58, 0x0, 0xc0004ca470, 0x9, 0xc000c2f5a0, 0x3480c88, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.9/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000c41840, 0x0, 0xed40aba58, 0x0, 0xc0004ca470, 0x9, 0xc000c2f5a0, 0x3480c88, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.9/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0066d4488, 0xb, 0x0, 0x0, 0x0, 0xc0004ca470, 0x9, 0x8b9058, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0066d4488, 0x24ca738, 0xc000176340, 0x1, 0x0)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x24c62d8, 0xc000c40820, 0xb, 0x0, 0x0, 0x0, 0xc0004ca470, 0x9, 0x8b9058, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.9/node/node.go:293 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000d8e780, 0x24a5770, 0xc000f534a0, 0xc000c40fe0, 0x246d3e0, 0xc00000e4b0, 0xc000c41050, 0x224f010, 0xc000c41140, 0x24af2f0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.9/node/node.go:700 +0x1ee5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000dd3780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24b81d0, 0xc000d64580, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:244 +0x585
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000db7600, 0xc000e65da0, 0x0, 0x1, 0x0, 0x0)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:120 +0x1c8
github.com/spf13/cobra.(*Command).execute(0xc000db7600, 0xc000e65d90, 0x1, 0x1, 0xc000db7600, 0xc000e65d90)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d6e580, 0x0, 0x0, 0xc000d07810)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000d6e580, 0xc000d07810, 0xb, 0x24cd2f8, 0xc000d64580)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/server/cmd/execute.go:36 +0x265
main.main()
	/data/iris-node-1.1.1/src/cmd/iris/main.go:17 +0x45
```

**Comment by Xiechengqi** [comment]
Here is my install script link - https://raw.githubusercontent.com/Xiechengqi/scripts/master/install/IRIS/iris-node/install.sh

**Comment by Xiechengqi** [comment]
I tried 1.0.0 and 1.1.1，the same ERROR result

**Comment by chengwenxi** [comment]
You can run `iris unsafe-reset-all` and then start it via v1.0.1, follow this document https://github.com/irisnet/irishub/blob/master/docs/get-started/mainnet.md.

**Comment by Xiechengqi** [comment]
> You can run `iris unsafe-reset-all` and then start it via v1.0.1, follow this document https://github.com/irisnet/irishub/blob/master/docs/get-started/mainnet.md.

the same result
``` shell
root@ip-172-26-10-12:/data/IRIS/iris-node# iris unsafe-reset-all
10:22AM INF Removed all blockchain history dir=/root/.iris/data
10:22AM INF Generated private validator file keyFile=/root/.iris/config/priv_validator_key.json stateFile=/root/.iris/data/priv_validator_state.json
root@ip-172-26-10-12:/data/IRIS/iris-node# iris start --home=/data/IRIS/iris-node/data
10:22AM INF starting ABCI with Tendermint
10:22AM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:22AM INF Starting localClient service connection=query impl=localClient module=abci-client
10:22AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:22AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:22AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:22AM INF Starting EventBus service impl=EventBus module=events
10:22AM INF Starting PubSub service impl=PubSub module=pubsub
10:22AM INF Starting IndexerService service impl=IndexerService module=txindex
10:22AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
10:22AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
10:22AM INF asserting crisis invariants inv=0/11 module=x/crisis name=gov/module-account
10:22AM INF asserting crisis invariants inv=1/11 module=x/crisis name=bank/nonnegative-outstanding
10:22AM INF asserting crisis invariants inv=2/11 module=x/crisis name=bank/total-supply
10:22AM INF asserting crisis invariants inv=3/11 module=x/crisis name=staking/module-accounts
10:22AM INF asserting crisis invariants inv=4/11 module=x/crisis name=staking/nonnegative-power
10:22AM INF asserting crisis invariants inv=5/11 module=x/crisis name=staking/positive-delegation
10:22AM INF asserting crisis invariants inv=6/11 module=x/crisis name=staking/delegator-shares
10:22AM INF asserting crisis invariants inv=7/11 module=x/crisis name=distribution/nonnegative-outstanding
10:22AM INF asserting crisis invariants inv=8/11 module=x/crisis name=distribution/can-withdraw
10:22AM INF asserting crisis invariants inv=9/11 module=x/crisis name=distribution/reference-count
10:22AM INF asserting crisis invariants inv=10/11 module=x/crisis name=distribution/module-account
10:22AM INF asserted all invariants duration=5578.637904 height=9146456 module=x/crisis
10:22AM INF created new capability module=ibc name=ports/transfer
10:22AM INF port binded module=x/ibc/port port=transfer
10:22AM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: unknown field "pending_htlcs" in types.GenesisState

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0011122d0, 0xc0010949d8, 0x14, 0x18, 0x2493830, 0xc0052ff560)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/codec/proto_codec.go:160 +0x98
github.com/irisnet/irismod/modules/htlc.AppModule.InitGenesis(0x24bf278, 0xc0011122d0, 0x2482ec8, 0xc000132ad0, 0x24bf278, 0xc0011122d0, 0x24b8798, 0xc0011122d0, 0xc000d66028, 0x2482ec8, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/irisnet/irismod@v1.4.0/modules/htlc/module.go:138 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000d87570, 0x24a0728, 0xc0000560b0, 0x24b80d0, 0xc000af7000, 0x0, 0x0, 0xc000ad2470, 0x9, 0x8b9058, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/types/module/module.go:304 +0x2b5
github.com/irisnet/irishub/app.(*IrisApp).InitChainer(0xc000b90c00, 0x24a0728, 0xc0000560b0, 0x24b80d0, 0xc000af7000, 0x0, 0x0, 0xc000ad2470, 0x9, 0x8b9058, ...)
	/data/IRIS/iris-node-1.1.0/src/app/app.go:646 +0x5d0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000e89860, 0x0, 0xed40aba58, 0x0, 0xc000ad2470, 0x9, 0xc000c2d580, 0x346fa88, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/baseapp/abci.go:62 +0x2f5
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000c92d20, 0x0, 0xed40aba58, 0x0, 0xc000ad2470, 0x9, 0xc000c2d580, 0x346fa88, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.8/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000b51810, 0x0, 0xed40aba58, 0x0, 0xc000ad2470, 0x9, 0xc000c2d580, 0x346fa88, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.8/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc006638498, 0xb, 0x0, 0x0, 0x0, 0xc000ad2470, 0x9, 0x8b9058, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.8/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc006638498, 0x24bc6b8, 0xc00016e270, 0x1, 0x0)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.8/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x24b82d8, 0xc000b50420, 0xb, 0x0, 0x0, 0x0, 0xc000ad2470, 0x9, 0x8b9058, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.8/node/node.go:277 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000da8640, 0x2497970, 0xc00014c1e0, 0xc000aef7c0, 0x245f720, 0xc00000e4b0, 0xc000aef830, 0x2241f38, 0xc000aef920, 0x24a1410, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.8/node/node.go:685 +0x1e65
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000dd5740, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24aa1d0, 0xc000d60500, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:244 +0x585
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000db5600, 0xc000e63d20, 0x0, 0x1, 0x0, 0x0)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/server/start.go:120 +0x1c8
github.com/spf13/cobra.(*Command).execute(0xc000db5600, 0xc000e63d10, 0x1, 0x1, 0xc000db5600, 0xc000e63d10)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d6c580, 0x0, 0x0, 0xc000d057f0)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000d6c580, 0xc000d057f0, 0xb, 0x24bf278, 0xc000d60500)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.3/server/cmd/execute.go:36 +0x265
main.main()
	/data/IRIS/iris-node-1.1.0/src/cmd/iris/main.go:17 +0x45
root@ip-172-26-10-12:/data/IRIS/iris-node# 

```

**Comment by chengwenxi** [comment]
@Xiechengqi What's the iris version?
```sh
iris version
```

**Comment by Xiechengqi** [comment]
Thanks a lot,  Understand error ！- https://github.com/irisnet/irishub/issues/2638
