### ISSUE TITLE
加入测试网 - panic: unknown field "restricted_service_fee_denom" in types.Params

### ISSUE THREAD

**Issue by Xiechengqi** [irisnet/irishub#2644]
**Describe the bug**
按照 https://www.irisnet.org/docs/zh/get-started/testnet.html 将节点加入测试网失败，报错

**To Reproduce**
* Ubuntu18.04
* Go 1.16.6
* Iris 1.0.1
* 空系统首次安装运行即报错，执行 `iris unsafe-reset-all --home=/data/IRIS/iris/data` 后在执行启动命令还是报如下错误

``` shell
root@ip-172-26-6-195:/data/IRIS/iris/data# iris start --home=/data/IRIS/iris-node-1.0.1/data
4:05PM INF starting ABCI with Tendermint
4:05PM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
4:05PM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
4:05PM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
4:05PM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
4:05PM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
4:05PM INF Starting EventBus service impl={"Logger":{}} module=events
4:05PM INF Starting PubSub service impl={"Logger":{}} module=pubsub
4:05PM INF Starting IndexerService service impl={"Logger":{}} module=txindex
4:05PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
4:05PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unknown field "restricted_service_fee_denom" in types.Params

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0010be250, 0xc00014ca00, 0x27f, 0x280, 0x2468570, 0xc000f701e0)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.3/codec/proto_codec.go:160 +0x98
github.com/irisnet/irishub/app.(*IrisApp).InitChainer(0xc000c1b500, 0x2474108, 0xc000054080, 0x248b7d0, 0xc000ae7c80, 0x0, 0x0, 0xc000054680, 0x9, 0x0, ...)
	/data/IRIS/iris-node-1.0.1/src/app/app.go:590 +0x19f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000e61860, 0x1153e8c, 0xed7f346e3, 0x0, 0xc000054680, 0x9, 0xc000bfdd00, 0x3433748, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.3/baseapp/abci.go:62 +0x2f5
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000c86300, 0x1153e8c, 0xed7f346e3, 0x0, 0xc000054680, 0x9, 0xc000bfdd00, 0x3433748, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.7/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000c248e0, 0x1153e8c, 0xed7f346e3, 0x0, 0xc000054680, 0x9, 0xc000bfdd00, 0x3433748, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.7/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000bae498, 0xb, 0x0, 0x0, 0x0, 0xc000054680, 0x9, 0x1, 0x0, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.7/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000bae498, 0x248fd30, 0xc0001196c0, 0x1, 0x0)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.7/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x248b9d8, 0xc000b509c0, 0xb, 0x0, 0x0, 0x0, 0xc000054680, 0x9, 0x1, 0x0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.7/node/node.go:277 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000f28000, 0x246b330, 0xc000f71040, 0xc000ae3c60, 0x2433680, 0xc00000e510, 0xc000ae3cd0, 0x221b8f0, 0xc000ae3dc0, 0x2474db8, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/tendermint/tendermint@v0.34.7/node/node.go:685 +0x1e65
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000dab780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x247d9b0, 0xc000d462d0, ...)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:244 +0x585
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000d89340, 0xc000e3fac0, 0x0, 0x1, 0x0, 0x0)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.3/server/start.go:120 +0x1c8
github.com/spf13/cobra.(*Command).execute(0xc000d89340, 0xc000e3fab0, 0x1, 0x1, 0xc000d89340, 0xc000e3fab0)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d7e000, 0x0, 0x0, 0xc000cd94a0)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/data/golang-1.16.6/path/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000d7e000, 0xc000cd94a0, 0xb, 0x24928f8, 0xc000d462d0)
	/data/golang-1.16.6/path/pkg/mod/github.com/cosmos/cosmos-sdk@v0.41.3/server/cmd/execute.go:36 +0x265
main.main()
	/data/IRIS/iris-node-1.0.1/src/cmd/iris/main.go:17 +0x45
root@ip-172-26-6-195:/data/IRIS/iris/data#
```

**Expected behavior**

* 希望官方文档认真完善补充下，安装部署过程一步一个坑，节点加入测试网就有两篇文档（[快速开始](https://www.irisnet.org/docs/zh/get-started/testnet.html)和[本地测试网](https://www.irisnet.org/docs/zh/daemon/local-testnet.html))，两篇部署步骤不同，而且【快速开始】的加入【测试网络】“偷工减料”，建议【快速开始】里的【加入测试网络】重复的部署过程也写上，这样能避免很多理解上的歧义
* 希望节点启动成功，同步测试网 Nyancat

* 这个【除了】不理解，而且这段话与上下很难串起来，希望能多加些解释
![image](https://user-images.githubusercontent.com/26536442/127892995-4118cb1f-4ec2-4a23-8951-0439eb4d3dcc.png)

**Comment by chengwenxi** [comment]
@Xiechengqi Thanks for your report! It would be great if you can submit a PR to improve this document.

**Comment by chengwenxi** [comment]
Resolved via #2656
