### ISSUE TITLE
Snapshots not working following v1.4.1 upgrade

### ISSUE THREAD

**Issue by Jackson-DKMG** [irisnet/irishub#2791]
After the upgrade to v1.4.1, the nodes crash when taking snapshots, causing the snapshots to be incomplete (only 2 files created), and therefore making it impossible to statesync.

Here is the error. Tested with a binary compiled with go18.1 and go19.3, same behavior. No option change in the node configuration allowed to circumvent the issue.
I couldn't statesync from the foundation RPCs, but unsure whether they have the same problem or not.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe4a033]

goroutine 450 [running]:
github.com/cosmos/iavl.(*nodeDB).incrVersionReaders(0x32bf060?, 0x20?)
        /home/iris/go/pkg/mod/github.com/cosmos/iavl@v0.19.4/nodedb.go:943 +0x33
github.com/cosmos/iavl.newExporter(0xc01b94d640)
        /home/iris/go/pkg/mod/github.com/cosmos/iavl@v0.19.4/export.go:46 +0xc8
github.com/cosmos/iavl.(*ImmutableTree).Export(...)
        /home/iris/go/pkg/mod/github.com/cosmos/iavl@v0.19.4/immutable_tree.go:159
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Export(0xc024174a50?, 0x32a93f0?)
        /home/iris/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.5/store/iavl/store.go:282 +0x52
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Snapshot(0xc000f99080, 0x10e0226, {0x329a560, 0xc004512210})
        /home/iris/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.5/store/rootmulti/store.go:742 +0x5be
github.com/cosmos/cosmos-sdk/snapshots.(*Manager).createSnapshot(0xc001508ea0, 0xc001508ea0?, 0x10e0226?)
        /home/iris/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.5/snapshots/manager.go:199 +0xb1
created by github.com/cosmos/cosmos-sdk/snapshots.(*Manager).Create
        /home/iris/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.5/snapshots/manager.go:181 +0x2a5`

This is somewhat problematic -- the nodes can't be pruned and will require an increasing storage space, while the data can't be reduced by statesyncing (and quicksync snapshot will become too big to manage shortly).

**Comment by kingli-crypto** [comment]
Same issue

**Comment by aofengli** [comment]
Please set `pruning` in `apptoml` to `pruning = noting`

**Comment by Jackson-DKMG** [comment]
It is already the case -- otherwise the node panics when it tries to prune.

**Comment by aofengli** [comment]
> It is already the case -- otherwise the node panics when it tries to prune.

Don't worry, we will update a version to fix this problem as soon as possible.
