### ISSUE TITLE
【upgrades】During the upgrade from 2.1 to 3.0, the upgrade fails and a panic error is reported

### ISSUE THREAD

**Issue by huang0227** [irisnet/irishub#2931]
**Describe the bug**
Upgrade from 2.1 to 3.0 After the proposal is approved, when the upgrade height is reached, a panic: runtime error: invalid memory address or nil pointer dereference is reported when the startup chain of the 3.0 client is replaced
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17fd810]

**To Reproduce**
Initiate the upgrade and vote for it. Initiate a deal of untying. Initiate a parameter modification proposal. When the upgrade height is reached, the parameter modification proposal is in the voting process (I do not know whether it is relevant). Replace the 3.0 client startup chain.
error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17fd810]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade/types.UpgradeStoreLoader.func1({0x42951c8, 0xc0006a0400})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.11-ics-lsm/x/upgrade/types/storeloader.go:15 +0x50
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).LoadLatestVersion(0xc0000770e0)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.11-ics-lsm/baseapp/baseapp.go:306 +0x2d
github.com/irisnet/irishub/v3/app.NewIrisApp({0x4257ed8, 0xc000da3d00}, {0x4272a18, 0xc0013864c0}, {0x0, 0x0}, 0x1, {{0x4263fd0, 0xc001451ea0}, {0x4288e20, ...}, ...}, ...)
	/home/huang/irishub/irishub/app/app.go:206 +0x128b
github.com/irisnet/irishub/v3/cmd/iris/cmd.appCreator.newApp({{{0x4263fd0, 0xc001451ea0}, {0x4288e20, 0xc0014a9380}, {0x426e660, 0xc0014e0380}, 0xc0000152b0}}, {0x4257ed8, 0xc000da3d00}, {0x4272a18, ...}, ...)
	/home/huang/irishub/irishub/cmd/iris/cmd/root.go:240 +0x112
github.com/evmos/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x4273e80, 0xc001a97260}, 0x0, {0x0, 0x0}, {0x4288e20, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/xxxai/ethermint@v0.22.0-irishub-20231207.0.20240419023144-3cea3d782107/server/start.go:353 +0xb03
github.com/evmos/ethermint/server.StartCmd.func2(0xc0018cec00?, {0xc0019bf020?, 0x0?, 0x2?})
	/root/go/pkg/mod/github.com/xxxai/ethermint@v0.22.0-irishub-20231207.0.20240419023144-3cea3d782107/server/start.go:159 +0x225
github.com/spf13/cobra.(*Command).execute(0xc0018cec00, {0xc0019bf000, 0x2, 0x2})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc001835200)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2d11500?, {0x0, 0x0}, {0xc0014a3ff0, 0xb})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.11-ics-lsm/server/cmd/execute.go:33 +0x1a5
main.main()
	/home/huang/irishub/irishub/cmd/iris/main.go:17 +0x30

**Expected behavior**
Can be upgraded successfully

**Screenshots**
![image](https://github.com/irisnet/irishub/assets/14272473/f7f62a6b-6049-4d67-8128-79e45cc0edd6)

**Comment by huang0227** [comment]
The proposal name should say v3, not v3.0.   Relaunch the proposal, no problem
