### ISSUE TITLE
[priority:p0]Stake unbond fail to properly handle boundary values, in certain cases, validator will be trapped in "Unbonding" Status FOREVER !! (This defect affects CONSENSUS)

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#963]
Start 2 nodes (voting power: v0=100, v1=100)

Detailed steps
-----------------
iriscli keys show v1 --bech val
fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 

echo 1234567890 | iriscli stake delegate --address-validator=fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 --amount=5iris --fee=0.004iris --commit  --from=v0 --chain-id=shilei-qa

echo 1234567890 | iriscli stake unbond --address-validator=fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 --shares-amount=99.9999999999 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

echo 1234567890 | iriscli stake unbond --address-validator=fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 --shares-percent=0.9999999999 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

echo 1234567890 | iriscli stake unbond --address-validator=fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 --shares-percent=0.9999999999 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

At this moment, v1 status :
**----------------------------------
Jailed: true
Status: Unbonding
Tokens: 5.000000000000000001
Delegator Shares: 5.000000000000000000
----------------------------------**

echo 1234567890 | iriscli stake delegate --address-validator=fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 --amount=5iris --fee=0.004iris --commit  --from=v1 --chain-id=shilei-qa

echo 1234567890 | iriscli stake unjail --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

echo 1234567890 | iriscli stake unbond --address-validator=fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 --shares-percent=1 --fee=0.004iris --commit --from=v0 --chain-id=shilei-qa

At this moment, v1 status :
**----------------------------------
Jailed: false
Status: Bonded
Tokens: 5.000000000000000001
Delegator Shares: 5.000000000000000000
----------------------------------**

echo 1234567890 | iriscli stake unbond --address-validator=fva1elqfurnh8rvv3fsa4l9ytenwmqxx6mqxfl68z2 --shares-amount=5 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

**----------------------------------
Jailed: true
Status: Unbonding
Tokens: 0.000000000000000001
Delegator Shares: 0.000000000000000000
----------------------------------**

At this moment, v1 fall into "Unbonding" state and looks like it will be trapped in this Status **FOREVER !!**

Since v1 was trapped in such kind of "Unbonding" state, an attempt to unjail v1 will trigger CONSENSUS FAILURE !

echo 1234567890 | iriscli stake unjail --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

CONSENSUS FAILURE !

[2016-01-02|17:14:54.022] CONSENSUS FAILURE!!!                         module=consensus err="Should not delete validator with unwithdrawn delegator accum" stack="goroutine 111 [running]:\nruntime/debug.Stack(0xc0009919f0, 0xe8f0e0, 0x128a750)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000a06000, 0x119a0b0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xe8f0e0, 0x128a750)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/modules/distribution/keeper.Keeper.RemoveValidatorDistInfo(0x1296300, 0xc0001b1e00, 0xc0000c6380, 0xc0000c6380, 0x1296300, 0xc0001b1e60, 0x1296340, 0xc0001b1e70, 0xc0000b9480, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/distribution/keeper/validator.go:42 +0x31c\ngithub.com/irisnet/irishub/modules/distribution/keeper.Keeper.onValidatorRemoved(0x1296300, 0xc0001b1e00, 0xc0000c6380, 0xc0000c6380, 0x1296300, 0xc0001b1e60, 0x1296340, 0xc0001b1e70, 0xc0000b9480, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/distribution/keeper/hooks.go:54 +0xc2\ngithub.com/irisnet/irishub/modules/distribution/keeper.Hooks.OnValidatorRemoved(0x1296300, 0xc0001b1e00, 0xc0000c6380, 0xc0000c6380, 0x1296300, 0xc0001b1e60, 0x1296340, 0xc0001b1e70, 0xc0000b9480, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/distribution/keeper/hooks.go:110 +0xc2\ngithub.com/irisnet/irishub/app/v0.Hooks.OnValidatorRemoved(0x1296300, 0xc0001b1e00, 0xc0000c6380, 0xc0000c6380, 0x1296300, 0xc0001b1e60, 0x1296340, 0xc0001b1e70, 0xc0000b9480, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:400 +0xf2\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.RemoveValidator(0x1296300, 0xc0001b1dd0, 0x1296340, 0xc0001b1de0, 0xc0000c6380, 0x12a9380, 0xc000afbc60, 0x12a67e0, 0xc000b54ea0, 0xc0000c6380, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/validator.go:202 +0x57b\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.UnbondAllMatureValidatorQueue(0x1296300, 0xc0001b1dd0, 0x1296340, 0xc0001b1de0, 0xc0000c6380, 0x12a9380, 0xc000afbc60, 0x12a67e0, 0xc000b54ea0, 0xc0000c6380, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/validator.go:392 +0x613\ngithub.com/irisnet/irishub/modules/stake.EndBlocker(0x129e9e0, 0xc002f950e0, 0xc0035d5080, 0xd, 0x1296300, 0xc0001b1dd0, 0x1296340, 0xc0001b1de0, 0xc0000c6380, 0x12a9380, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/handler.go:50 +0x128\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker(0xc0000a8300, 0x129e9e0, 0xc002f950e0, 0xc0035d5080, 0xd, 0x3f, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:253 +0x14d\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker-fm(0x129e9e0, 0xc002f950e0, 0xc0035d5080, 0xd, 0x3f, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:375 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc000165ee0, 0x3f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:834 +0x809\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000af6f00, 0x3f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc000a89970, 0x3f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x129f760, 0xc0001890a0, 0x12a4bc0, 0xc000a89970, 0xc0034a0960, 0xc002f94a50, 0x12a9200, 0xc00000e148, 0xa, 0xc0030c1400, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000bf6000, 0x8, 0x0, 0xc000a5d2f0, 0x6, 0xc000a5d300, 0x9, 0x3e, 0xa, 0xc0030c1400, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000a06000, 0x3f)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000a06000, 0x3f)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000a06000, 0x0, 0x3f)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000a06000, 0x3f, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000a06000, 0xc003a86000, 0x0, 0x0, 0x4c665d, 0xc003770cc0, 0xc000a82200)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000a06000, 0xc003a86000, 0x0, 0x0, 0x42cc82, 0xc000000008, 0xc000995b70)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000a06000, 0x1292e20, 0xc000a559c8, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000a06000, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:623 +0x567\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Comment by HaoyangLiu** [comment]
Once https://github.com/irisnet/irishub/pull/986 is merged, please recheck this issue.

**Comment by shilei-wang** [comment]
Bug still exist， keep issue open

**Comment by HaoyangLiu** [comment]
It seems that this issue has some connection with validator jail. If no validator jail happens, then the `CONSENSUS FAILURE` won't happen. I'm still working on this issue.

**Comment by HaoyangLiu** [comment]
This issue is very interesting. The reproduce steps can be simplified as follows:

Suppose there is a 2-nodes blockchain network, each voting power is 100, validators marked as v0 and v1, validator operators marked as d0 and d1, then follow these steps:

1. d0 delegate some token to v1
2. d1 unbond all tokens from v1
3. d1 delegate some token to v1
4. d1 unjail v1
5. d0 unbond all token from v1
6. d1 unbond all token from v1
