### ISSUE TITLE
[priority:p0] Not taking "slashing_periods" into consideration, any attempt to unbond a validator totally after Class 4 Upgrade may cause CONSENSUS FAILURE!

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#969]
Describe the bug
It seems export not taking "slashing_periods" into consideration.

**To Reproduce**

    1. start iris with 2 nodes.
    2. Stop/Export/Restart 2 nodes
    3. echo 1234567890 | iriscli stake unbond --address-validator=fva10m900my3yltnwmc0t2awmuqxkgymucyhmfvmw9 --shares-percent=1 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

    CONSENSUS FAILURE !

Expected behavior
Unbond smoothly

Screenshots
[3016-01-03|18:51:16.693] CONSENSUS FAILURE!!!                         module=consensus err="expected to find slashing period for validator fca1ghf49af6tuq4fysk7e90mnfsh8p4uvdq8enfh4 before height 9, but none was found" stack="goroutine 92 [running]:\nruntime/debug.Stack(0xc0021e3388, 0xe91060, 0xc0027d75f0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000083c00, 0x119c1f0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xe91060, 0xc0027d75f0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/modules/slashing.Keeper.getValidatorSlashingPeriodForHeight(0x1298540, 0xc00006c150, 0xc00081e000, 0x12a9300, 0xc0007f0280, 0xc00081e000, 0x1298540, 0xc00006c1b0, 0x1298580, 0xc00006c1d0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/slashing/slashing_period.go:48 +0x4b4\ngithub.com/irisnet/irishub/modules/slashing.Keeper.onValidatorBeginUnbonding(0x1298540, 0xc00006c150, 0xc00081e000, 0x12a9300, 0xc0007f0280, 0xc00081e000, 0x1298540, 0xc00006c1b0, 0x1298580, 0xc00006c1d0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/slashing/hooks.go:36 +0x10a\ngithub.com/irisnet/irishub/modules/slashing.Hooks.OnValidatorBeginUnbonding(0x1298540, 0xc00006c150, 0xc00081e000, 0x12a9300, 0xc0007f0280, 0xc00081e000, 0x1298540, 0xc00006c1b0, 0x1298580, 0xc00006c1d0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/slashing/hooks.go:73 +0xf2\ngithub.com/irisnet/irishub/app/v0.Hooks.OnValidatorBeginUnbonding(0x1298540, 0xc00006c120, 0xc00081e000, 0xc00081e000, 0x1298540, 0xc00006c1b0, 0x1298580, 0xc00006c1d0, 0xc000bcdb00, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:409 +0x1b5\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.beginUnbondingValidator(0x1298540, 0xc00006c0e0, 0x1298580, 0xc00006c0f0, 0xc00081e000, 0x12ab600, 0xc000ba59c0, 0x12a8a60, 0xc0001ec6c0, 0xc00081e000, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/val_state_change.go:238 +0x84e\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.bondedToUnbonding(0x1298540, 0xc00006c0e0, 0x1298580, 0xc00006c0f0, 0xc00081e000, 0x12ab600, 0xc000ba59c0, 0x12a8a60, 0xc0001ec6c0, 0xc00081e000, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/val_state_change.go:132 +0x104\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.ApplyAndReturnValidatorSetUpdates(0x1298540, 0xc00006c0e0, 0x1298580, 0xc00006c0f0, 0xc00081e000, 0x12ab600, 0xc000ba59c0, 0x12a8a60, 0xc0001ec6c0, 0xc00081e000, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/val_state_change.go:109 +0xd2e\ngithub.com/irisnet/irishub/modules/stake.EndBlocker(0x12a0c20, 0xc0027ce030, 0xc0027be300, 0xd, 0x1298540, 0xc00006c0e0, 0x1298580, 0xc00006c0f0, 0xc00081e000, 0x12ab600, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/handler.go:47 +0x95\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker(0xc000b0aa00, 0x12a0c20, 0xc0027ce030, 0xc0027be300, 0xd, 0x9, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:251 +0x150\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker-fm(0x12a0c20, 0xc0027ce030, 0xc0027be300, 0xd, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:368 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc0007ec0c0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:829 +0x809\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000954660, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc000bc9340, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x12a1a20, 0xc0008ccd20, 0x12a6e40, 0xc000bc9340, 0xc0022a4f00, 0xc002457920, 0x12ab480, 0xc0001b2120, 0x0, 0xc002418640, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0008cff80, 0x8, 0x0, 0xc0000b73b0, 0x6, 0xc0000b73c0, 0x9, 0x8, 0x0, 0xc002418640, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000083c00, 0x9)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000083c00, 0x9)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000083c00, 0x0, 0x9)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000083c00, 0x9, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000083c00, 0xc002453180, 0xc000a0e090, 0x28, 0x119d428, 0x107, 0xc0021e7ac0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000083c00, 0xc002453180, 0xc000a0e090, 0x28, 0xc000b62900, 0x107, 0x107)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000083c00, 0x1295060, 0xc0001b2d48, 0xc000a0e090, 0x28)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000083c00, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:619 +0x682\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

Desktop (please complete the following information):

    2 validator nodes

Smartphone (please complete the following information):
N/A

Additional context
N/A

**Comment by HaoyangLiu** [comment]
https://github.com/irisnet/irishub/pull/913 will fix this issue. Once it is merged, please recheck this issue.

**Comment by shilei-wang** [comment]
verified
