### ISSUE TITLE
[priority:p0]Trying to slash an unbonded validator causes CONSENSUS break! We don't take special case into account While we trying to slash non-vote validators.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#979]
**Special case should/must be considered ! Unbonded validator should be excluded from collections.**

To reproduce:
1) v0-power=100 , v1-power=100
2) submit-proposal
3) vote start        : v_set_A = {v0, v1}
4) voting period  : unbond v1(percent 99.6%)， no one vote
5) vote end         : v_set_B = {v0, v1(unbonded)}
6) slash v_set_A ∩ v_set_B  = slash {v0, v1(unbonded)}   ??? !!! ???
7) CONSENSUS break

------------------------
message:

CONSENSUS FAILURE!!!                         module=consensus err="should not be slashing unbonded validator: fva1gu04tqwlt4y40mrs3h608gjymrmveazrrcultl" stack="goroutine 107 [running]:\nruntime/debug.Stack(0xc000a0d8a8, 0xe90f00, 0xc000b92f20)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc00008b880, 0x119c230)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xe90f00, 0xc000b92f20)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.Slash(0x1298ac0, 0xc000243660, 0x1298b00, 0xc000243670, 0xc00020ebd0, 0x12abb80, 0xc000aa1940, 0x12a8fe0, 0xc0000f18c0, 0xc00020ebd0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/slash.go:63 +0x1cb2\ngithub.com/irisnet/irishub/modules/gov.EndBlocker(0x12a11a0, 0xc002797980, 0xc002df0ac0, 0xd, 0x1298ac0, 0xc0002436c0, 0xc00020ebd0, 0xc00020ebd0, 0x1298ac0, 0xc0002436e0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/handler.go:291 +0x1ed0\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker(0xc000254700, 0x12a11a0, 0xc002797980, 0xc002df0ac0, 0xd, 0x44, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:267 +0xc1\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker-fm(0x12a11a0, 0xc002797980, 0xc002df0ac0, 0xd, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:385 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc000b3c240, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:829 +0x89d\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0009e51a0, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc000a253b0, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x12a1fa0, 0xc00089f7e0, 0x12a73c0, 0xc000a253b0, 0xc00013f680, 0xc002797350, 0x12aba00, 0xc0001ce510, 0x3, 0xc002f6f600, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000922460, 0x8, 0x0, 0xc000895bb0, 0x6, 0xc000895bc0, 0x9, 0x43, 0x3, 0xc002f6f600, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc00008b880, 0x44)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc00008b880, 0x44)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc00008b880, 0x0, 0x44)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc00008b880, 0x44, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc00008b880, 0xc003a34460, 0x0, 0x0, 0x4c665d, 0xc002e35b60, 0xc000a48200)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc00008b880, 0xc003a34460, 0x0, 0x0, 0x42cc82, 0xc000000008, 0xc000a11b70)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc00008b880, 0x1295660, 0xc002b07248, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc00008b880, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:623 +0x567\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Comment by shilei-wang** [comment]
verified
