### ISSUE TITLE
[priority:p0] Trying to govern the upper limit numbers of validator casues CONSENSUS break!

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#989]
Once proposal passed, err="Type mismatch with registered table", CONSENSUS break!

To reproduce:

echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='stake/MaxValidators=101' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

echo 1234567890 | iriscli gov vote --option=Yes --fee=0.004iris --commit --from=v0 --chain-id=shilei-qa  --proposal-id=1

---------------
msg:
CONSENSUS FAILURE!!!                         module=consensus err="Type mismatch with registered table" stack="goroutine 14 [running]:\nruntime/debug.Stack(0xc000478110, 0xe90f00, 0x128d240)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000a47180, 0x119c230)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xe90f00, 0x128d240)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/modules/params/subspace.Subspace.Set(0xc000212000, 0x1298ac0, 0xc00006cfc0, 0x1298b00, 0xc00006cfd0, 0xc0000343c0, 0x5, 0x8, 0xc000b01ce0, 0x12a11a0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/params/subspace/subspace.go:131 +0x3d4\ngithub.com/irisnet/irishub/modules/gov.ParameterProposalExecute(0x12a11a0, 0xc00293b800, 0xc002ac2600, 0xd, 0x1298ac0, 0xc00006cfa0, 0xc000212000, 0xc000212000, 0x1298ac0, 0xc00006cfc0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/execute.go:48 +0x85e\ngithub.com/irisnet/irishub/modules/gov.Execute(0x12a11a0, 0xc00293b800, 0xc002ac2600, 0xd, 0x1298ac0, 0xc00006cfa0, 0xc000212000, 0xc000212000, 0x1298ac0, 0xc00006cfc0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/execute.go:12 +0xe1\ngithub.com/irisnet/irishub/modules/gov.EndBlocker(0x12a11a0, 0xc00293b800, 0xc002ac2600, 0xd, 0x1298ac0, 0xc00006cfa0, 0xc000212000, 0xc000212000, 0x1298ac0, 0xc00006cfc0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/handler.go:268 +0x2398\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker(0xc000228000, 0x12a11a0, 0xc00293b800, 0xc002ac2600, 0xd, 0x11, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:267 +0xc1\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker-fm(0x12a11a0, 0xc00293b800, 0xc002ac2600, 0xd, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:385 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc00020a0c0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:829 +0x89d\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0000bde60, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc00006d920, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x12a1fa0, 0xc00084ecc0, 0x12a73c0, 0xc00006d920, 0xc0029385a0, 0xc00293b1d0, 0x12aba00, 0xc0001b2338, 0x2, 0xc002a5ce80, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000851ea0, 0x8, 0x0, 0xc000b35470, 0x6, 0xc000b35480, 0x9, 0x10, 0x2, 0xc002a5ce80, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000a47180, 0x11)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000a47180, 0x11)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000a47180, 0x0, 0x11)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000a47180, 0x11, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000a47180, 0xc002918820, 0x0, 0x0, 0x4c665d, 0xc00291cde0, 0xc0001f2c00)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000a47180, 0xc002918820, 0x0, 0x0, 0x42cc82, 0xc000000008, 0xc00047bb70)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000a47180, 0x1295660, 0xc0009018d8, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000a47180, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:623 +0x567\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Comment by chengwenxi** [comment]
Please verify and close
